name: Trigger auto deployment for deezxmr

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/deezxmr-AutoDeployTrigger-99a26f55-4f66-459f-ac9b-a175b6b6749e.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: deezcon.azurecr.io
          username: ${{ secrets.DEEZXMR_REGISTRY_USERNAME }}
          password: ${{ secrets.DEEZXMR_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: deezcon.azurecr.io/deezxmr:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DEEZXMR_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n deezxmr -g DefaultResourceGroup-CCAN --server deezcon.azurecr.io --username  ${{ secrets.DEEZXMR_REGISTRY_USERNAME }} --password ${{ secrets.DEEZXMR_REGISTRY_PASSWORD }}
            az containerapp update -n deezxmr -g DefaultResourceGroup-CCAN --image deezcon.azurecr.io/deezxmr:${{ github.sha }}
